<?php

namespace BackendBundle\Repository;

/**
 * AutorisationABSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorisationABSRepository extends \Doctrine\ORM\EntityRepository
{
}
