<?php

namespace BackendBundle\Repository;

/**
 * ChefEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefEquipeRepository extends \Doctrine\ORM\EntityRepository
{
}
