<?php

namespace BackendBundle\Repository;

/**
 * CongesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongesRepository extends \Doctrine\ORM\EntityRepository
{
}
